version: "3.10"
services:
  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
  restaurant-service: # The name: restaurant-service_restaurant-service_1 -> Because the folder is restaurant-service
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb # Connected through services container name
    depends_on:
      - mongodb